### ISSUE TITLE
New pattern not working well for grappa3.m

### ISSUE THREAD

**Issue by QQRider** [marcsous/parallel#1]
Hi Mark,

I'm using your grappa3.m for my project. It works well and fast for 2x2 acceleration. However, I have data that 3x for ky and 2x for kz, when I pass this 'pattern',{[1 0 1;0 0 0;0 0 0 ;1 0 1]}' into the function, the function seemed to run, but the image result still have severe aliasing. I'm not sure how to use it well. Could you give me a hint? 

Thanks for your time.
Yishi

**Comment by marcsous** [comment]
Hi Yishi,

Sorry you're running into problems. I had a quick test on some data and indeed it does not seem to work with 3x acceleration in any direction. I guess I never tested 3x...! Fortunately the problem is simple to fix (and I will add it to the code in a day or two).

The convolution kernels need to have a "center" point, which means the length has to be an odd number. Therefore pad a zero on either end of the even dimension. Also for separable acceleration patterns, GRAPPA works well doing each dimension in turn.

Try the following:

```
    mask = false(size(data,1),size(data,2),size(data,3));

    mask(:,1:3:end,1:2:end) = 1; % undersample 3x2
    
    pattern{1} = [1 0 0 1 0]'; % y first pass (with padded zero)
    pattern{2} = [1 0 1]'; % y second pass
    pattern{3} = [1 0 1]; % z first pass
    
    varargin{1} = 'pattern';
    varargin{2} = pattern;
```
Thanks for your message! Appreciated :)
Mark

**Comment by marcsous** [comment]
Updated the code - it should work now without needing zero padding.

**Comment by QQRider** [comment]
Hi Mark,


Thanks for the updating. I just tested it with my data of 3*2 undersampling and it works fine. 
I still have two questions regarding the definition of pattern and pass. I don't quite understand the concept of first pass or second pass
For example, for this regular 3*2 pattern, I can understand | 1 0 1| and [ 1 0 0 1]', but I don't see [1 0 1]' shown in the red box. This also confused me for pattern 2*2 shifted. 
If I need a pattern with 3*1, how should I define it in the function?


Thanks!
Yishi







--

Wang Yishi,Ph.D.

Center for Biomedical Imaging Research

Department of Biomedical Engineering

School of Medicine,Tsinghua University

Beijing,100084

E-mail: ***@***.***




At 2023-09-25 14:44:12, "Mark Bydder" ***@***.***> wrote:

Hi Yishi,

Sorry you're running into problems. I had a quick test on some data and indeed it does not seem to work with 3x acceleration in any direction. I guess I never tested 3x...! Fortunately the problem is simple to fix (and I will add it to the code in a day or two).

The convolution kernels need to have a "center" point, which means the length has to be an odd number. Therefore pad a zero on either end of the even dimension. Also for separable acceleration patterns, GRAPPA works well doing each dimension in turn.

Try the following:

    mask = false(size(data,1),size(data,2),size(data,3));

    mask(:,1:3:end,1:2:end) = 1; % undersample 3x2
    
    pattern{1} = [1 0 0 1 0]'; % y first pass (with padded zero)
    pattern{2} = [1 0 1]'; % y second pass
    pattern{3} = [1 0 1]; % z first pass
    
    varargin{1} = 'pattern';
    varargin{2} = pattern;


Thanks for your message! Appreciated :)
Mark

**Comment by marcsous** [comment]
3x1 would be [1;0;0;1] and [1;0;1].

If you have N patterns then the code will loop over the reconstruction N times. Each time it fills in some of the holes. E.g. if the sampled data is ...x o o x.... (3 x 1 acceleration) then after convolving with [1 0 0 1] it will be ....x o x x.... then after convolving with [1 0 1] it will be ...x x x x... . Those are the 2 passes.

I updated the comment in the code, hope it makes sense.
```
%% Convolution patterns (1D or 2D)
%
% Patterns tell the code which neighbors to use to construct
% the center point. E.g. [1 0 1] means use 2 neighbors along
% the z-direction to fill in the zero (resulting in [1 1 1]). 
% Patterns are not unique - they are just vectors in the SAKE
% nullspace - but some work better. 4 neighbors may be better
% than 2 but 8 may be worse. Several patterns are configured
% (see code around line 90).
```

**Comment by QQRider** [comment]
Hi Mark,


Thanks for the explanation, that's really helpful.


Is there a parameter that can be tuned to increase SNR?


Best Regards,
Yishi













--

Wang Yishi,Ph.D.

Center for Biomedical Imaging Research

Department of Biomedical Engineering

School of Medicine,Tsinghua University

Beijing,100084

E-mail: ***@***.***




At 2023-09-27 00:48:09, "Mark Bydder" ***@***.***> wrote:

3x1 would be [1;0;0;1] and [1;0;1].

If you have N patterns then the code will loop over the reconstruction N times. Each time it fills in some of the holes. E.g. if the sampled data is ...x o o x.... (3 x 1 acceleration) then after convolving with [1 0 0 1] it will be ....x o x x.... then after convolving with [1 0 1] it will be ...x x x x... . Those are the 2 passes.

I updated the comment in the code, hope it makes sense.

%% Convolution patterns (1D or 2D)
%
% Patterns tell the code which neighbors to use to construct
% the center point. E.g. [1 0 1] means use 2 neighbors along
% the z-direction to fill in the zero (resulting in [1 1 1]). 
% Patterns are not unique - they are just vectors in the SAKE
% nullspace - but some work better. 4 neighbors may be better
% than 2 but 8 may be worse. Several patterns are configured
% (see code around line 90).

**Comment by QQRider** [comment]
Hi Mark,
I tried to use the GPU option. The great thing is, it's really fast compared to CPU. However, the reconstructed image showed severe SNR loss compared to CPU. I'm not quite sure how to use it in the right way. 
Below is a comparison, the image on the left was reconstructed using CPU, and the image on the right was by GPU. 

Could you point me in the right way of using it? If the GPU recon works as well as CPU, it would be super nice.


Best Regards,
Yishi







--

Wang Yishi,Ph.D.

Center for Biomedical Imaging Research

Department of Biomedical Engineering

School of Medicine,Tsinghua University

Beijing,100084

E-mail: ***@***.***




At 2023-09-27 09:00:40, "voyage" ***@***.***> wrote:

Hi Mark,


Thanks for the explanation, that's really helpful.


Is there a parameter that can be tuned to increase SNR?


Best Regards,
Yishi













--

Wang Yishi,Ph.D.

Center for Biomedical Imaging Research

Department of Biomedical Engineering

School of Medicine,Tsinghua University

Beijing,100084

E-mail: ***@***.***




At 2023-09-27 00:48:09, "Mark Bydder" ***@***.***> wrote:

3x1 would be [1;0;0;1] and [1;0;1].

If you have N patterns then the code will loop over the reconstruction N times. Each time it fills in some of the holes. E.g. if the sampled data is ...x o o x.... (3 x 1 acceleration) then after convolving with [1 0 0 1] it will be ....x o x x.... then after convolving with [1 0 1] it will be ...x x x x... . Those are the 2 passes.

I updated the comment in the code, hope it makes sense.

%% Convolution patterns (1D or 2D)
%
% Patterns tell the code which neighbors to use to construct
% the center point. E.g. [1 0 1] means use 2 neighbors along
% the z-direction to fill in the zero (resulting in [1 1 1]). 
% Patterns are not unique - they are just vectors in the SAKE
% nullspace - but some work better. 4 neighbors may be better
% than 2 but 8 may be worse. Several patterns are configured
% (see code around line 90).
